name: LLMe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - python-dotenv
  - pip:
    - transformers
    - openai
    - gradio
    - anthropic
    - faiss-cpu
    - langchain
    - langchain-community
    - langchain-openai
